Document: icdiff
Title: Debian icdiff Manual
Author: <insert document author here>
Abstract: This manual describes what icdiff is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/icdiff/icdiff.sgml.gz

Format: postscript
Files: /usr/share/doc/icdiff/icdiff.ps.gz

Format: text
Files: /usr/share/doc/icdiff/icdiff.text.gz

Format: HTML
Index: /usr/share/doc/icdiff/html/index.html
Files: /usr/share/doc/icdiff/html/*.html
